### ISSUE TITLE
App crashes when i try calling louvre to pick images

### ISSUE THREAD

**Issue by KelvinPac** [andremion/Louvre#25]
```
Process: com.example.kelvin.m_nyumbabeta, PID: 10436
                                                                                 java.lang.NoSuchFieldError: No field recycler_view of type I in class Lcom/andremion/louvre/R$id; or its superclasses (declaration of 'com.andremion.louvre.R$id' appears in /data/app/com.example.kelvin.m_nyumbabeta-1/split_lib_slice_2_apk.apk)
                                                                                     at com.andremion.louvre.home.GalleryFragment.onCreateView(GalleryFragment.java:169)
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                                     at android.support.v4.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManager.java:1655)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1390)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1650)
                                                                                     at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1906)
                                                                                     at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3698)
                                                                                     at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
                                                                                     at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:350)
                                                                                     at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
                                                                                     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                     at com.andremion.louvre.home.GalleryActivity.onCreate(GalleryActivity.java:115)
                                                                                     at android.app.Activity.performCreate(Activity.java:6955)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
                                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6836)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by andremion** [comment]
Could you follow the [Issue Template](/andremion/Louvre/blob/development/ISSUE_TEMPLATE.md) or provide more information such as:

- Which version of library are you using?
- This error occurs in compile time or runtime?
- Are you using proguard?

Thanks

**Comment by andremion** [comment]
Closed by no answer
