### ISSUE TITLE
Crash in android 10

### ISSUE THREAD

**Issue by hosnyDev** [andremion/Louvre#29]
**when click to openGallery app is crash .**

```
Caused by: android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT bucket_id, bucket_display_name, _data FROM images WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' )) AND (_data>'')) AND ((1 AND 1) GROUP BY (1)) ORDER BY MAX(datetaken) DESC
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:41)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-06-15 23:51:51.346 2943-2943/com.dpmuae.aklaClient E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
2020-06-15 23:51:51.635 2943-2943/com.dpmuae.aklaClient E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
```

**Comment by SlonGL** [comment]
Hello,

Same error and on Android 10 also

**Comment by alexburkhay** [comment]
Confirmed, library crashes every time if you have target sdk 29 in the app (which is required from nov 2020), so its unusable and read/populate from db needs to be rewritten. 
https://stackoverflow.com/questions/60623594/replacement-for-group-by-in-contentresolver-query-in-android-q-android-10-a

**Comment by andremion** [comment]
Thanks for reporting!
I just pushed a release with a possible solution https://bintray.com/andremion/github/Louvre/1.3.0
Please let me know if there's any side-effect.

**Comment by andremion** [comment]
Done in https://github.com/andremion/Louvre/releases/tag/v1.3.0
